### ISSUE TITLE
Bug Report: Post not showing up

### ISSUE THREAD

**Issue by carolynshin** [githubtraining/github-pages#23]
## Bug Report

**Current behavior**
Post not showing up.

**Reproduction**
Steps to reproduce the behavior in the course:
1. Go to this issue: https://github.com/carolynshin/github-pages-with-jekyll/pull/4, which tells me that I successfully completed the course.
2. Go to my page: https://carolynshin.github.io/github-pages-with-jekyll/
3. See error: No post

**Expected behavior**
I expected [my post](https://github.com/carolynshin/github-pages-with-jekyll/blob/master/_posts/2019-08-15-my.md) to show up on my [page](https://carolynshin.github.io/github-pages-with-jekyll/) but I do not see it. 

**Possible solution**
N/A

**Additional context**
Another user on the learning lab community forum experienced this problem. It is most likely because there are issues with their post - they didn't add a space between the date and the date value, and it looks like they added their blog content inside the frontmatter. I was testing out this course to see if it fixed the user's issue and couldn't get my post to work either.

/cc: @hectorsector and @a-a-ron

**Comment by a-a-ron** [comment]
Thanks @carolynshin. I'm currently looking into it

**Comment by a-a-ron** [comment]
Hey @carolynshin, this issue is occurring because of the `minimal` theme we are using. It doesn't appear to handle "Posts" the way the course had intended. Looking through the course history we changed it a few times but originally we had theme `minima`. I went through the course using this theme and I was able to get the course to show my posts as expected. We will want to push up a fix for this - probably changing the theme back to `minima`.
