### ISSUE TITLE
The Class Completes Successfully Even with Pages Compilation Error

### ISSUE THREAD

**Issue by amyschoen** [githubtraining/github-pages#30]
## Bug Report

**Current behavior**
The course doesn't detect compilation errors in jekyll.

**Reproduction**
Steps to reproduce the behavior in the course:

Step 4: Customize Site Details
1. Start the value for `github_username` in `_config.yaml` with an `@`.
2. Finish the rest of the instructions and eventually merge in the PR.
3. You receive an email notification that looks like this:

```
The page build failed for the `master` branch with the following error:
You have an error on line 9 of your `_config.yml` file. For more information, see https://help.github.com/enterprise/2.19/user/en/articles/troubleshooting-jekyll-build-errors-for-github-pages-sites#config-file-error.
For information on troubleshooting Jekyll see:
  https://help.github.com/enterprise/2.19/user/articles/troubleshooting-jekyll-builds
If you have any questions you can contact us by replying to this email.
```
4. The course still congratulates you on successful completion.

**Expected behavior**
I would expect that an issue with the config file would not lead to successful course completion.

**Possible solution**
Find some way of detecting that pages didn't get deployed correctly and have them go back and edit.

**Additional context**
N/A

/cc @crichID  @brianamarie @hectorsector @JasonEtco

**Comment by brianamarie** [comment]
I was able to recreate this. I would also expect that this would get caught. I see a few possible ways we could address this:

| Solution | Pros | Cons |
| ----- | --- | --- |
| 1. Change the final step from a merge to a page build, with a gate for the build being successful. If it's not successful, we can do a troubleshooting guide. | Very thorough, and could introduce the learner to more ways to troubleshoot Jekyll | Will take longer to implement, and Jekyll problems are a big can of worms that we may not want to open. User already does have access to this information via email if it does happen. |
| 2. The links to the social aren't a key part of the course. We could also remove these from the template. | Simple solution - if we can avoid the problem, then we don't have to solve it. | Taking away the tangential learning opportunity for noticing that social links can be included in a Jekyll config |
| 3. If we keep the links to the social, we could include in commented text to `#be sure _not_ to include the @ symbol, or the build will fail | Middle ground between introducing users to Jekyll troubleshooting, and removing the fields completely. Easy and quick to implement, and still introduces troubleshooting concept and idea that incorrect syntax in config file will cause Jekyll build failures. | Not checking the build ourselves may lead the user to discovering their build has failed through email instead of through Learning Lab |

@amyschoen I'm leaning towards option 3 right now because of it's simple execution. I am going to go ahead and change this now in the template repository. 

Considering this hasn't been an issue to come up in our support email or through the community forum before this, do you think this is a sufficient solution at this time?

**Comment by brianamarie** [comment]
I've made this update and re-synced the course repository ✅ https://github.com/githubtraining/github-pages-with-jekyll-template/commit/ae84fb26857fecb754dc32006d013ae3d8ea9a81

**Comment by amyschoen** [comment]
👍 from me on going with option 3.  We're probably signing up for way too much and overcomplicating things if we get into troubleshooting Jekyll.  I'm thinking that's likely beyond the target audience of this course.

**Comment by brianamarie** [comment]
Sounds good. I'll close this issue.
