### ISSUE TITLE
Add support for Git LFS

### ISSUE THREAD

**Issue by radzo73** [githubtraining/github-pages#33]
## Feature Request

**Describe the problem/friction you are trying to solve**
Currently, GitHub Pages does not load content properly when said content is hosted by Git LFS. (for example, https://radzo73.github.io/fparchive/FPAW1.html loads its Flash .swf just fine because the .swf isn't hosted on Git LFS, but https://radzo73.github.io/fparchive/FPAW3.html doesn't load its Flash .swf properly because its .swf *is* hosted with Git LFS)

**Describe your ideal solution.**
Git LFS support, so files on my GitHub Page load properly (for example, again, https://radzo73.github.io/fparchive/FPAW3.html would load its Flash .swf properly if Git LFS support was added.)

**Drawbacks:** None?

**Describe alternatives you have considered.**
Adding/using alternatives to Git LFS (nothing that I know of)

**Comment by brianamarie** [comment]
Thank you for opening this issue, @radzo73! I didn't know that GitHub Pages wouldn't load content stored using LFS.

I have passed this feedback along internally to the teams working on GitHub Pages. I am going to close this issue for now, because this repository is specifically about the course on Learning Lab. If you have any other context or information you'd like me to pass on, please let me know. 😊
